### ISSUE TITLE
Reimplement footer buttons for Moodle 4.0

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodle-tool_moodlebox#103]
Buttons in the footer do not work anymore on Moodle 4.0.

**Comment by martignoni** [comment]
Related discussion on moodle.org: https://moodle.org/mod/forum/discuss.php?d=434012.

**Comment by ralf-krause** [comment]
Hi Nicolas,
perhaps you will get help from the code for the Moodle plugin "Boost Union". https://github.com/moodle-an-hochschulen/moodle-theme_boost_union

I just tested the plugin "Boost Union" to get some advanced settings for a web site with Moodle 4.0.2. You can set the course width to 1200px, you can set a favicon and you can add a footline. Currently you can see the footline with a button on a test page https://elisl.org/test40/

Best regards, Ralf

**Comment by ralf-krause** [comment]
Please look also at https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/6

**Comment by martignoni** [comment]
@ralf-krause: thanks for your help, but this will not work, as it seems plugins cannot override renderers (only themes can do that).

The plugin footer with buttons should work for any (Boost-based at least) theme, so we must find a way to do it in the plugin.
