### ISSUE TITLE
Wrong dashboard view after changewifisettings

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodle-tool_moodlebox#126]
I am testing MoodleBox 4.6.0. I found that I get a wrong dashboard view after I changed the MoodleBox ip address. 

I set the regulation country to Germany and the static ip address to 10.10.10.1. My connected laptop md-lap-3011 gets an ip address 10.10.10.131 … this is correct. The laptop wifi settings show this ip address and the correct router ip address 10.10.10.1. The MoodleBox dashboard still shows the static ip address 10.0.0.1. There is also shown an older ip address for Tab-S6-Lite-von-Ralf which should be deleted when the ip address changed.

![moodlebox-10-10-10-1-b](https://github.com/moodlebox/moodle-tool_moodlebox/assets/27956839/a77e9da3-117d-43a3-b123-5502f5aa80f2)

![moodlebox-10-10-10-1](https://github.com/moodlebox/moodle-tool_moodlebox/assets/27956839/42503c0d-0d04-4aea-834c-a9f526f5bee7)

**Comment by martignoni** [comment]
The bug with regulatory country is fixed in version v.2.17.2 of the plugin.

**Comment by martignoni** [comment]
See #128 for progress on item 3 in [above comment](https://github.com/moodlebox/moodle-tool_moodlebox/issues/126#issuecomment-1828311182).

**Comment by martignoni** [comment]
Closing, since the related issues are fixed and released.
