### ISSUE TITLE
Wrong version date and release in version.php for version 2.18.2

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodle-tool_moodlebox#146]
To install the new version of this plugin into the MoodleBox I download the code as a zip file. 

I open the page http://moodlebox.home/admin/tool/installaddon/index.php from the administration menu and move the zip file into the drop field. Clicking the install button Moodle shows that the validation is successful and the installation can continue. But no database action happens ... okay, there is no database action required because the change is only in a copied file. I read the version.php. 
```
$plugin->version  = 2024101300;
$plugin->release = '2.18.1';
$plugin->requires = 2018120300;
$plugin->supported = [404, 405];
$plugin->maturity = MATURITY_STABLE;
$plugin->component = 'tool_moodlebox';
```
If the $plugin->version would be 2024101301 then a user would get the normal installation with database action. Yes, this is no bug.

The setting $plugin->requires = 2018120300 means that the plugin needs Moodle 3.6 (2018120300). You write that the current MoodleBox plugin 2.18.1 does not work except with Moodle 4.4 and 4.5. So the setting $plugin->requires should be 2024042200. The developer doc says that _It is not possible to install the plugin on an earlier version of Moodle._
Because the setting $plugin->supported = [404, 405] was new in Moodle 3.9 the plugin could be installed in Moodle 3.6 to 3.8 without an error message ... yes, it will not work but the installation could happen. 
https://moodledev.io/docs/4.1/apis/commonfiles/version.php

**Comment by martignoni** [comment]
These are 2 separate issues. I've opened issue #147 for the wrong `$plugin->requires` value.
