### ISSUE TITLE
MoodleBox wifi does not connect with Raspberry Pi 3B

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodle-tool_moodlebox#150]
## Prerequisites

- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Describe the bug
In my MoodleBox workshop I want to show different Raspberry Pi (4B, 3B+, 3B) with the MoodleBox 4.7.0 image. For my workshop I installed some courses an some test users so the participants can use some activities. Using BalenaEtcher I cloned the microSD master on some other microSD cards so that the different Raspberry Pi models should work.

I found the the Raspberry Pi 3B can't be connected with my mobile devices. I get the error "Anmeldung erforderlich" with a password input field on my Linux laptop. And my iPhone says "Wrong password for MoodleBox". The password is correct but the wifi does not connect. Is there a problem with the Raspberry Pi OS? 

Yes, I installed a fresh copy of the image moodlebox-4.7.0.img.xz on another microSD card but I get the same result.

### To Reproduce
To reproduce this error you will need a Raspberry Pi 3B.

## Additional context
- Raspberry Pi model [RPi 3B]
- MoodleBox version 4.7.0
- MoodleBox plugin version 2.17.5 (the preinstalled plugin version)

**Comment by martignoni** [comment]
OK, this is the same issue as #145. Please follow up there.
