### ISSUE TITLE
Make restart and shutdown buttons more accessible

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodle-tool_moodlebox#33]
Idea suggested here: https://moodle.org/mod/forum/discuss.php?d=362704.

Possibilities:
- New block plugin, or
- Current plugin injects the buttons via JS.

(Issue cloned from: https://github.com/martignoni/moodlebox/issues/50.)

**Comment by martignoni** [comment]
See https://docs.moodle.org/dev/Output_callbacks#before_footer.

Example in Moodle source code: function tool_usertours_before_footer() in /tool/usertours/lib.php.

**Comment by martignoni** [comment]
Don't forget to add an option, so that users can opt-out from having those buttons displayed.

**Comment by adpe** [comment]
Sound's interesting. What about a solution, if the button are displayed for site-admins in the navigation drawer instead of a block?

**Comment by martignoni** [comment]
Also a possibility. My idea was to display those buttons for the admin only, on __every page__ (in the footer).

**Comment by adpe** [comment]
The contact form isn't working on https://moodlebox.net, therefore I contacted you private on https://moodle.org.

**Comment by martignoni** [comment]
Tested. Works as described.

**Comment by martignoni** [comment]
All done. Closing.

A big thank you to @adpe.
