### ISSUE TITLE
Support of RPi 3B+

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodle-tool_moodlebox#39]
Add detection of Raspberry Pi 3B+.

**Comment by martignoni** [comment]
See commits c3715f8 and 526ddb4.

**Comment by martignoni** [comment]
Waiting my RPi3B+ to test this.

**Comment by martignoni** [comment]
Closing as fixed.

**Comment by ralf-krause** [comment]
Hello Nicolas,
the plugin has the version number 1.10. But in AMOS I can‘t see the text string for the Raspberry Pi 3B+.
Ralf

**Comment by martignoni** [comment]
You're right. Though it's present in the release (so you see it in the GUI), it is not present in AMOS. I suspect that AMOS can't interpret correctly the "+" sign in a string key.

Will ask in AMOS forum about this.

**Comment by ralf-krause** [comment]
I think you must change the text Id to someting like rpi3b-plus.
$string['rpi3b+'] = 'Raspberry Pi 3 model B+';

**Comment by martignoni** [comment]
> I suspect that AMOS can't interpret correctly the "+" sign in a string key.

Indeed.

**Comment by martignoni** [comment]
@ralf-krause: I just cut a new release with a fix (see #40). Thanks for the heads up.
