### ISSUE TITLE
Enable partition resizing in GUI

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodle-tool_moodlebox#45]
Hi Nicolas,
for my workshops I am using my own MoodleBox image. I take your image but I add some Moodle plugins and some Moodle courses to get my workshop setting. I copy this image to some sd cards to use more than only one MoodleBox. And I want to give away my image to my participants so they can start their own MoodleBox with my settings.
To be able to copy the image on all kinds of sd cards I shrinked the partition down to less than 8 GB. I can copy this image to cards with 8, 16 and 32 GB ... or more :-) Yes, it‘s no problem for me to enlarge the partition in Terminal. But most of my participants who want to get their own MoodleBox only can copy the image to the sd card. They can‘t use the Terminal to enlarge the partition size.

What do you think about the following idea. I want to get a button in the MoodleBox plugin which can enlarge the partition size. The button is avalable only when the sd card has some unused space. So also users will be able to copy their own MoodleBox image to a larger sd cards without open the Terminal. Mac users could use ApplePi Baker for backup the MoodleBox card and restore it to a larger one.

Best regards, Ralf

**Comment by martignoni** [comment]
Good idea. Will investigate.

**Comment by ralf-krause** [comment]
Hi Nicolas,
the new feature does not work for me. My sd card has 32 GB and my image uses 15 GB. I installed the new plugin version from git and restarted the MoodleBox. 
Clicking the new resize button I got the message that the MoodleBox will restart automatically to resize the disk space. My MoodleBox did not restart. So I restarted it manually but there was also no more disk space. When I choose the resize option with the terminal command raspi-config then I get the full disk space correctly.
Best regards, Ralf

**Comment by ralf-krause** [comment]
Okay, I found that I should add a line in the incrontab list before the new button will work.

**Comment by martignoni** [comment]
Thanks for the test. Can you confirm that the button did work after adding the incrontab job?

**Comment by ralf-krause** [comment]
Hi Nicolas,
yes, after adding the following line to the incrontab list I got the correct result.
`/var/www/moodle/admin/tool/moodlebox/.resize-partition IN_CLOSE_WRITE /bin/bash /var/www/moodle/admin/tool/moodlebox/bin/resizepartition.sh`
Is it possible to hide the button if the partition size is maximal?

**Comment by martignoni** [comment]
Thanks for the test.

Re: hiding the button. It could be possible, but with much more work. However, this is not too a problem, as you may click on the button without consequence even when the partition size is maximal. 

I'll try however to find if a quick solution is possible.

**Comment by ralf-krause** [comment]
The consequence is that the Moodlebox tries to resize the partition and then it will restart even if the partition was in maximal size before.

**Comment by martignoni** [comment]
Tried several ways to get unallocated space on SD card. Unfortunately, all possibilities need superuser permissions for finding this essential info, which is impractical as enabling these permissions for the web server user would be a big security hole.

I'm afraid this won't do it. However, the rebooting of the MoodleBox is not such a big deal :-).

**Comment by martignoni** [comment]
FYI, here's what I tried.

```php
    public static function unallocated_free_space() {
        $command = "parted /dev/mmcblk0 unit MB print free | grep 'Free Space' | tail -n1 | awk '{print $3}' | sed -e 's/MB$//'";
        $unallocatedfreespace = exec($command, $out);
        return $unallocatedfreespace;
    }
```

**Comment by martignoni** [comment]
Documentation written (fr, en). See https://github.com/moodlebox/moodlebox.net/commit/b7e93731e3b17f8584a528534637348d108bc196.

@ralf-krause: would you agree to translate this documentation in German?

**Comment by ralf-krause** [comment]
Hallo Nicolas, 
ich weiß nicht mehr genau, wie ich die deutsche Übersetzung über git auf die Seite bringe. Deswegen füge ich die Datei hier ein. 
Gruß Ralf

[resize-sdcard-partition.de.txt](https://github.com/moodlebox/moodle-tool_moodlebox/files/2177724/resize-sdcard-partition.de.txt)

**Comment by ralf-krause** [comment]
Thank you very much for this feature! Danke!

**Comment by ralf-krause** [comment]
If you upload the new plugin version to https://moodle.org/plugins/tool_moodlebox then I can translate the new text strings in AMOS.

**Comment by martignoni** [comment]
Closing as fixed.
