### ISSUE TITLE
Row background in System information table is wrong (section "DHCP clients")

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodle-tool_moodlebox#47]
Hi Nicolas,
it's a very small problem.  :-)  
In the row "DHCP clients" you should have a second column. 
The number of clients can be moved into the right column.

![moodlebox-clients](https://user-images.githubusercontent.com/27956839/41819381-ade5cf58-77bf-11e8-96fc-b8c841aa7b20.png)

**Comment by martignoni** [comment]
Yes, I've seen that. This is due to new foundation of Moodle 3.5 Boost theme.

**Comment by martignoni** [comment]
Closing as fixed.
