### ISSUE TITLE
The help text for SSID uses a wrong number of bytes

### ISSUE THREAD

**Issue by ralf-krause** [moodlebox/moodle-tool_moodlebox#53]
Help text for SSID is not correct: "The name of the Wi-Fi network (SSID) of the MoodleBox. The string must be a minimum of 8 bytes and a maximum of 32 bytes."

Also in the code comment this fact is not considered. The code allows from 1 to 32 bytes and this is correct.
```bash
# We want to check that it is valid, and between 8 and 32 bytes.`
[[ $NEWSSID =~ ^([0-9a-fA-F]{2}){1,32}$ ]] || NEWSSID="4d6f6f646c65426f78" # "MoodleBox"
```

**Comment by ralf-krause** [comment]
I think that the help text could be something like this-
The name of the Wi-Fi network (SSID) of the Moodlebox can be from 1 to 32 bytes long. Please remember that some characters are using more than 1 bytes, e.g. Emoji.

**Comment by martignoni** [comment]
Closing as fixed.
