### ISSUE TITLE
Add option to hide SSID

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodle-tool_moodlebox#56]
See [this forum discussion](https://discuss.moodlebox.net/d/11-consider-to-hide-the-wi-fi-network-name).

**Comment by adpe** [comment]
@martignoni: Can I contribute something or are you already working on it?

**Comment by martignoni** [comment]
I'm working on it, but as this is a Moodle plugin, if you've some experience of Moodle plugin programming, I'd be glad to look at your PR.

Be sure please to conform to the [Moodle coding style](https://docs.moodle.org/dev/Coding_style).

**Comment by martignoni** [comment]
Implementation done. Needs testing now.

**Comment by adpe** [comment]
Thanks for working on it. I copied the two lines manually to the `hostapd.conf`. So this automated init part is not covered by my tests. Here is my review:

[y] Syntax (I'm not so experienced, please take it with attention)
[y] Output (Expected result on admin view)
[y] Language (en/fr)
[-] Databases
[y] Testing (Does the function do what it should => Moodle plugin and Shell script)
[-] Security
[-] Performance and Clustering
[n] Documentation
[y] Git
[-] Third party code
[-] Sanity check
[-] Icons

Just some questions:
- How does the trigger work? I've noticed that the filepermissions and owner of `changewifisettings.sh` changed after saving new Wi-Fi settings. They're not anymore moodlebox:www-data, they're root:root.
- Does the german translation will be made with AMOS? Why isn't just `en` in the plugin and `fr` will done with AMOS too? Is there a reason?
- Would it not be better, if the `triggerfiles` will be ignored from `git`? Would make sense to add these to `.gitignore`.

**Comment by martignoni** [comment]
Thanks for this review 👍 

To your questions.

> How does the trigger work?

There's an `incron` job that checks if the hidden `triggerfile` is changed. In this case, the script `changewifisettings.sh` is launched and sets the adequate parameters in `hostapd.conf`.

> Does the german translation will be made with AMOS? Why isn't just en in the plugin and fr will done with AMOS too? Is there a reason?

The german translation is indeed done via AMOS (and other languages too), like in any Moodle plugin. The english file __must__ be in the source (as per Moodle coding way). I keep the french language file here for archive reasons (but the strings are also translated in AMOS).

> Would it not be better, if the triggerfiles will be ignored from git?

It was the case some time ago, but this broke the upgrade process. See issue #37.

**Comment by martignoni** [comment]
Tested. Works OK.
