### ISSUE TITLE
Wrong unit for RAM sizes in language strings

### ISSUE THREAD

**Issue by martignoni** [moodlebox/moodle-tool_moodlebox#72]
RAM sizes for RPi 4B are indicated as MB. This should be GB.

Discovered by @ralf-krause.

**Comment by ralf-krause** [comment]
I think you should delete the three wrong strings from the language file.

**Comment by martignoni** [comment]
@ralf-krause: Best practice in Moodle coding is not to delete strings, but to deprecate them, so that people with older version still sees an existing string (and its translation) instead of a placeholder and code warnings.

A deprecated string is not suppressed until several version releases.

See https://docs.moodle.org/dev/String_deprecation.
